### ISSUE TITLE
mind doing a new release with the update for the python3 change?

### ISSUE THREAD

**Issue by psifertex** [bowline90/Instruction_Slicer#3]
Otherwise the version in the plugin manager is currently broken

**Comment by c3r34lk1ll3r** [comment]
Hi, a created a new release tagged v1.1 (https://github.com/c3r34lk1ll3r/Instruction_Slicer/releases/tag/v1.1)

**Comment by psifertex** [comment]
Thanks. I've updated it in the plugin manager.
